with open("src/db/schema.sql", "a") as f:
    f.write("""
-- Add missing columns to products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_plus VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS subcategory_plus VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS discount NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS gst_plus VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS cgst NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS sgst NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS igst NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS sales_unit VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS sales_alt_unit VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS conv NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS min_stock NUMERIC(10, 3);
ALTER TABLE products ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS s_tax NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS p_tax NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS g_down VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS rack VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS def_qty NUMERIC(10, 3);
ALTER TABLE products ADD COLUMN IF NOT EXISTS part_no VARCHAR(100);
ALTER TABLE products ADD COLUMN IF NOT EXISTS update_button_column VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS delete_button_column VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS print_barcode_button VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS mark VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS photo TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS cmb_gst VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS hsn_sac_id UUID;
""")
