-- Add missing columns to retail_customers table
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS registration_type VARCHAR(50);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS pan VARCHAR(50);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS landmark TEXT;
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'India';
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS distance VARCHAR(50);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS customer_group VARCHAR(100);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS opening_balance NUMERIC(14,2) DEFAULT 0;
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS balance_type VARCHAR(20) DEFAULT 'Credit';
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS license_no VARCHAR(100);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS custom_field_1 TEXT;
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS custom_field_2 TEXT;
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS fax_no VARCHAR(50);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(14,2);
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS due_days INTEGER;
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE retail_customers ADD COLUMN IF NOT EXISTS enable BOOLEAN DEFAULT true;

-- Add missing columns to suppliers table
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS registration_type VARCHAR(50);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS pan VARCHAR(50);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS landmark TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'India';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS distance VARCHAR(50);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS supplier_group VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS opening_balance NUMERIC(14,2) DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS balance_type VARCHAR(20) DEFAULT 'Credit';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS license_no VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS custom_field_1 TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS custom_field_2 TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS fax_no VARCHAR(50);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(14,2);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS due_days INTEGER;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS enable BOOLEAN DEFAULT true;
